### ISSUE TITLE
Update Jekyll & Bulma

### ISSUE THREAD

**Issue by miklb** [erayaydin/jekyll-bulma#4]
I was in the process of creating a very similar project, when I discovered you had created a Jekyll theme for Bulma. I intend to use the [Bulma rails](https://github.com/joshuajansen/bulma-rails)

However, if you would like I can update for Bulma 0.5.1 and Jekyll 3.5.2 before I do. Would you be interested in a PR if I do? I know the navbar has probably changed along with a few other minor changes.

Eventually, I'm going to use the [bulma-rails](https://github.com/joshuajansen/bulma-rails) gem to manage Bulma, but I can wait to do that until after updating the core files in my fork.

Thanks for the work getting this going!

**Comment by erayaydin** [comment]
Hello,

Of course I'll accept PR :+1: Thank you for interest

**Comment by erayaydin** [comment]
Thank you for Pull Request, its merged
